### ISSUE TITLE
Failed to install Flixy on pythonista 3.3

### ISSUE THREAD

**Issue by ftourand** [SKbarbon/flixy#12]
Using Pythonista 3.3 (python 3.6)
I Create a .py file including the following,

import requests
exec(requests.get("https://bit.ly/flixy-installer").text);

Ran on ipad pro 11’’ - model MHQW3NF/A - ipados 16.4.1 - 320Gb available disk space

Experienced crash with the following message :

Exception in thread Thread-43:
Traceback (most recent call last):
  File "/var/containers/Bundle/Application/A70F941E-6EC6-49F3-9246-69E93A4063E1/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/var/containers/Bundle/Application/A70F941E-6EC6-49F3-9246-69E93A4063E1/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "<string>", line 267, in do_in_thread
  File "<string>", line 191, in SetTemplates
FileNotFoundError: [Errno 2] No such file or directory: '/private/var/mobile/Containers/Shared/AppGroup/AECE1AAC-2362-4084-982A-EBEE989C30C7/Pythonista3/Documents/Templates/flixy ui.py'

**Comment by SKbarbon** [comment]
Please, Can follow the another way on this video here:

https://user-images.githubusercontent.com/86029286/234991093-6d45bc55-adcf-4b00-a72f-b9cc7915893b.MOV

**Comment by alx-xlx** [comment]
I tried as shown in video, but getting similar error.

Running it on Pythonista v3.3,  ipad air 5
